information_system/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from information_system import settings
from information_system.apps.core import views as core_views

urlpatterns = [
    path("admin/", admin.site.urls),

    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', next_page='profile'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/logout.html'), name='logout'),

    path('profile/', core_views.profile, name='profile'),
    path('', core_views.index, name='index'),
    path('departments/', core_views.department_list, name='department_list'),
    path('devices/', core_views.device_list, name='device_list'),
    path('device_models/', core_views.device_model_list, name='device_model_list'),
    path('repairs/', core_views.repair_list, name='repair_list'),
    path('maintenance/', core_views.maintenance_list, name='maintenance_list'),

    path('repairs/create/', core_views.create_repair, name='create_repair'),
    path('repairs/<int:repair_id>/edit/', core_views.edit_repair, name='edit_repair'),
    path('repairs/<int:repair_id>/delete/', core_views.delete_repair, name='delete_repair'),

    path('maintenance/create/', core_views.create_maintenance, name='maintenance-create'),
    path('maintenance/<int:maintenance_id>/edit/', core_views.edit_maintenance, name='maintenance-edit'),
    path('maintenance/<int:maintenance_id>/delete/', core_views.delete_maintenance, name='maintenance-delete'),
    path('exchange_rates/', core_views.exchange_rates, name='exchange_rates'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()

information_system/apps/core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    Модель пользователя системы, расширяющая стандартную модель Django.
    """
    FIO = models.CharField(max_length=255, verbose_name="ФИО")
    email = models.EmailField(verbose_name="Email")
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    ROLE_CHOICES = (
        ('administrator', 'Администратор'),
        ('master', 'Мастер'),
        ('inspector', 'Проверяющий'),
    )
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, verbose_name="Роль")


class Department(models.Model):
    """
    Модель для хранения информации об отделениях почтовой связи.
    """
    name = models.CharField(max_length=255, verbose_name="Название")
    index = models.CharField(max_length=10, verbose_name="Индекс")
    phone = models.CharField(max_length=20, verbose_name="Номер телефона")
    TYPE_CHOICES = (
        ('city', 'Городское'),
        ('village', 'Сельское'),
        # ... другие типы отделений
    )
    type = models.CharField(max_length=20, choices=TYPE_CHOICES, verbose_name="Тип")
    district = models.CharField(max_length=255, verbose_name="Район")

    def __str__(self):
        return self.name


class DeviceType(models.Model):
    """
    Модель для хранения типов устройств.
    """
    name = models.CharField(max_length=255, verbose_name="Название типа")

    def __str__(self):
        return self.name


class DeviceModel(models.Model):
    """Модель устройства (общая информация)"""
    name = models.CharField(max_length=255, verbose_name="Модель")
    manufacturer = models.CharField(max_length=255, verbose_name="Производитель")
    description = models.TextField(blank=True, verbose_name="Описание")
    type = models.ForeignKey(DeviceType, on_delete=models.PROTECT, verbose_name="Тип")
    image = models.ImageField(upload_to='device_images/', blank=True, null=True, verbose_name="Изображение")

    def __str__(self):
        return f"{self.manufacturer} {self.name}"


class DeviceInstance(models.Model):
    """Экземпляр устройства (конкретное устройство)"""
    device_model = models.ForeignKey(DeviceModel, on_delete=models.CASCADE, verbose_name="Модель устройства")
    inventory_number = models.CharField(max_length=255, unique=True, verbose_name="Инвентарный номер")
    department = models.ForeignKey('Department', on_delete=models.CASCADE, verbose_name="Отделение связи")

    def __str__(self):
        return f"{self.inventory_number} ({self.device_model})"


class MaintenanceType(models.Model):
    """
    Модель для хранения типов технического обслуживания.
    """
    name = models.CharField(max_length=255, verbose_name="Название типа ТО")

    def __str__(self):
        return self.name


class Maintenance(models.Model):
    """
    Модель для хранения информации о техническом обслуживании.
    """
    date = models.DateField(verbose_name="Дата")
    device_instance = models.ForeignKey(DeviceInstance, on_delete=models.CASCADE, verbose_name="Устройство")
    type = models.ForeignKey(MaintenanceType, on_delete=models.PROTECT, verbose_name="Вид ТО")
    performed_by = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Работу выполнил")
    note = models.TextField(blank=True, verbose_name="Примечание")


class MalfunctionType(models.Model):
    """
    Модель для хранения типов неисправностей.
    """
    name = models.CharField(max_length=255, verbose_name="Название неисправности")

    def __str__(self):
        return self.name


class Repair(models.Model):
    """
    Модель для хранения информации о ремонтах.
    """
    date_breakdown = models.DateField(verbose_name="Дата поломки")
    device_instance = models.ForeignKey(DeviceInstance, on_delete=models.CASCADE, verbose_name="Устройство")
    malfunction_type = models.ForeignKey(MalfunctionType, on_delete=models.PROTECT,
                                         verbose_name="Характер неисправности")
    date_repair = models.DateField(null=True, blank=True, verbose_name="Дата устранения поломки")
    performed_by = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Ответственный")
    note = models.TextField(blank=True, verbose_name="Примечание")

information_system/apps/core/views.py
from datetime import timedelta, datetime

import openpyxl
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import F, Value
from django.db.models.functions import Concat
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect

from information_system.apps.core.forms import RepairForm, MaintenanceForm
from information_system.apps.core.models import Department, DeviceModel, DeviceInstance, DeviceType, Repair, \
    Maintenance, MalfunctionType, User, MaintenanceType


def index(request):
    return render(request, 'core/index.html')


@login_required
def profile(request):
    user = request.user

    recent_repairs = Repair.objects.filter(performed_by=user).order_by('-date_repair')[:5]

    recent_maintenance = Maintenance.objects.filter(performed_by=user).order_by('-date')[:5]

    total_repairs = Repair.objects.filter(performed_by=user).count()
    total_maintenance = Maintenance.objects.filter(performed_by=user).count()

    last_month = datetime.now() - timedelta(days=30)
    monthly_repairs = Repair.objects.filter(performed_by=user, date_repair__gte=last_month).count()
    monthly_maintenance = Maintenance.objects.filter(performed_by=user, date__gte=last_month).count()

    context = {
        'user': user,
        'recent_repairs': recent_repairs,
        'recent_maintenance': recent_maintenance,
        'total_repairs': total_repairs,
        'total_maintenance': total_maintenance,
        'monthly_repairs': monthly_repairs,
        'monthly_maintenance': monthly_maintenance,
    }

    return render(request, 'core/profile.html', context)


def department_list(request):
    departments = Department.objects.all()
    selected_department = None
    devices_in_department = []

    if request.GET.get('department'):
        selected_department = get_object_or_404(Department, pk=request.GET.get('department'))
        devices_in_department = DeviceInstance.objects.filter(department=selected_department).select_related(
            'device_model')

    context = {
        'departments': departments,
        'selected_department': selected_department,
        'devices_in_department': devices_in_department,
    }
    return render(request, 'core/department_list.html', context)


def device_list(request):
    devices = DeviceModel.objects.all()
    context = {'devices': devices}
    return render(request, 'core/device_list.html', context)


def device_model_list(request):
    device_models = DeviceModel.objects.all().select_related('type')
    device_types = DeviceType.objects.all()
    selected_device_model = None
    device_instances = []

    if request.GET.get('device_type'):
        selected_device_type = get_object_or_404(DeviceType, pk=request.GET.get('device_type'))
        device_instances = DeviceInstance.objects.filter(device_model__type=selected_device_type).select_related(
            'device_model')

    if request.GET.get('device_model'):
        selected_device_model = get_object_or_404(DeviceModel, pk=request.GET.get('device_model'))
        device_instances = DeviceInstance.objects.filter(device_model=selected_device_model)

    context = {
        'device_models': device_models,
        'device_types': device_types,
        'selected_device_model': selected_device_model,
        'device_instances': device_instances,
    }
    return render(request, 'core/device_model_list.html', context)


def repair_list(request):
    queryset = Repair.objects.all().select_related(
        'device_instance', 'device_instance__device_model', 'performed_by', "malfunction_type"
    )

    device_name = request.GET.get('device_name')
    inventory_number = request.GET.get('inventory_number')
    date_breakdown_start = request.GET.get('date_breakdown_start')
    date_breakdown_end = request.GET.get('date_breakdown_end')
    device_type = request.GET.get('device_type')
    malfunction_type = request.GET.get('malfunction_type')
    performed_by = request.GET.get('performed_by')
    department = request.GET.get('department')

    if device_name:
        queryset = (
            queryset
            .annotate(full_name=Concat(
                F('device_instance__device_model__manufacturer'),
                Value(' '),
                F('device_instance__device_model__name')
            ))
            .filter(full_name__icontains=device_name)
        )

    if inventory_number:
        queryset = queryset.filter(device_instance__inventory_number=inventory_number)

    if date_breakdown_start:
        queryset = queryset.filter(date_breakdown__gte=date_breakdown_start)

    if date_breakdown_end:
        queryset = queryset.filter(date_breakdown__lte=date_breakdown_end)

    if device_type:
        queryset = queryset.filter(device_instance__device_model__type_id=device_type)

    if malfunction_type:
        queryset = queryset.filter(malfunction_type_id=malfunction_type)

    if performed_by:
        queryset = queryset.filter(performed_by_id=performed_by)

    if department:
        queryset = queryset.filter(device_instance__department_id=department)

    repairs = queryset

    if "submit" in request.GET:
        device_types = DeviceType.objects.all()
        malfunction_types = MalfunctionType.objects.all()
        users = User.objects.all()
        departments = Department.objects.all()

        context = {'repairs': repairs, 'device_types': device_types, 'malfunction_types': malfunction_types,
                   'users': users,
                   'departments': departments}
        return render(request, 'core/repair_list.html', context)
    if "export" in request.GET:
        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = 'attachment; filename="repairs.xlsx"'

        workbook = openpyxl.Workbook()
        worksheet = workbook.active
        worksheet.title = "Ремонты"

        # Заголовки столбцов
        columns = [
            "Дата поломки", "Устройство", "Тип неисправности", "Дата устранения", "Выполнил", "Примечание"
        ]
        for col_num, column_title in enumerate(columns, 1):
            cell = worksheet.cell(row=1, column=col_num)
            cell.value = column_title

        # Данные
        for row_num, repair in enumerate(queryset, 2):  # Начинаем со второй строки
            worksheet.cell(row=row_num, column=1).value = repair.date_breakdown.strftime('%Y-%m-%d')
            worksheet.cell(row=row_num, column=2).value = str(repair.device_instance)
            worksheet.cell(row=row_num, column=3).value = str(repair.malfunction_type)
            worksheet.cell(row=row_num, column=4).value = repair.date_repair.strftime(
                '%Y-%m-%d') if repair.date_repair else ""  # Проверка на None
            worksheet.cell(row=row_num, column=5).value = str(repair.performed_by.FIO)
            worksheet.cell(row=row_num, column=6).value = repair.note

        workbook.save(response)

        return response
    else:
        device_types = DeviceType.objects.all()
        malfunction_types = MalfunctionType.objects.all()
        users = User.objects.all()
        departments = Department.objects.all()

        context = {'repairs': repairs, 'device_types': device_types, 'malfunction_types': malfunction_types,
                   'users': users,
                   'departments': departments}
        return render(request, 'core/repair_list.html', context)


def maintenance_list(request):
    queryset = Maintenance.objects.all().select_related('device_instance', 'device_instance__device_model',
                                                        'performed_by', 'type')

    device_name = request.GET.get('device_name')
    inventory_number = request.GET.get('inventory_number')
    date_breakdown_start = request.GET.get('date_breakdown_start')
    date_breakdown_end = request.GET.get('date_breakdown_end')
    device_type = request.GET.get('device_type')
    malfunction_type = request.GET.get('malfunction_type')
    performed_by = request.GET.get('performed_by')
    department = request.GET.get('department')

    if inventory_number:
        queryset = queryset.filter(device_instance__inventory_number=inventory_number)

    if device_name:
        queryset = (
            queryset
            .annotate(full_name=Concat(
                F('device_instance__device_model__manufacturer'),
                Value(' '),
                F('device_instance__device_model__name')
            ))
            .filter(full_name__icontains=device_name)
        )

    if inventory_number:
        queryset = queryset.filter(device_instance__inventory_number=inventory_number)

    if date_breakdown_start:
        queryset = queryset.filter(date__gte=date_breakdown_start)

    if date_breakdown_end:
        queryset = queryset.filter(date__lte=date_breakdown_end)

    if device_type:
        queryset = queryset.filter(device_instance__device_model__type_id=device_type)

    if malfunction_type:
        queryset = queryset.filter(type__name=malfunction_type)

    if performed_by:
        queryset = queryset.filter(performed_by_id=performed_by)

    if department:
        queryset = queryset.filter(device_instance__department_id=department)

    maintenances = queryset
    device_types = DeviceType.objects.all()
    maintenance_types = MaintenanceType.objects.all()
    users = User.objects.all()
    device_instances = DeviceInstance.objects.all()
    departments = Department.objects.all()

    if 'submit' in request.GET:
        context = {
            'maintenances': maintenances,
            'device_types': device_types,
            'maintenance_types': maintenance_types,
            'users': users,
            'device_instances': device_instances,
            'departments': departments,
        }
        return render(request, 'core/maintenance_list.html', context)
    if "export" in request.GET:

templates/core/create_maintenance.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Создать ТО</h1>

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

templates/core/create_repair.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Создать запись о ремонте</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.date_breakdown|as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.device_instance|as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.malfunction_type|as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.date_repair|as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.performed_by|as_crispy_field }}
        </div>
        <div class="form-group">
            {{ form.note|as_crispy_field }}
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock %}

templates/core/department_list.html
{% extends 'base.html' %}

{% block content %}

    <h1>Справочник отделений почтовой связи</h1>

    <div class="row mt-4">
        <div class="col-md-2">
            <div class="list-group border-bottom scrollarea">
                {% for department in departments %}
                    <a class="list-group-item list-group-item-action {% if department == selected_department %}active{% endif %}"
                       href="{% url 'department_list' %}?department={{ department.id }}">
                        {{ department.name }}
                    </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-10">
            {% if selected_department %}
                <h2>{{ selected_department.name }}</h2>
                <p>Индекс: {{ selected_department.index }}</p>
                <p>Телефон: {{ selected_department.phone }}</p>
                <p>Тип: {{ selected_department.get_type_display }}</p>
                <p>Район: {{ selected_department.district }}</p>


                <h3>Зарегистрированные устройства</h3>
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Тип устройства</th>
                        <th>Модель устройства</th>
                        <th>Инвентарный номер</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for device in devices_in_department %}
                        <tr>
                            <td>{{ device.device_model.type }}</td>
                            <td>{{ device.device_model.name }}</td>
                            <td>{{ device.inventory_number }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Выберите отделение из списка слева.</p>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/core/device_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Список устройств</h1>
    <p>Выберите раздел в меню, чтобы продолжить.</p>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Инвентарный номер</th>
      <th>Название</th>
      <th>Тип</th>
      <th>Описание</th>
      <th>Отделение связи</th>
    </tr>
  </thead>
  <tbody>
    {% for device in devices %}
    <tr>
      <td>{{ device.inventory_number }}</td>
      <td>{{ device.name }}</td>
      <td>{{ device.type }}</td>
      <td>{{ device.description }}</td>
      <td>{{ device.department }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/core/device_model_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Справочник устройств</h1>
    <div class="row mt-4">
        <div class="col-md-3">
            <div class="list-group border-bottom scrollarea">
                {% for device_type in device_types %}
                    <a class="list-group-item list-group-item-action d-flex justify-content-between {% if device_type == selected_device_type %}active{% endif %}"
                       data-bs-toggle="collapse" href="#collapse{{ device_type.id }}"
                       role="button"
                       aria-expanded="false" aria-controls="collapse{{ device_type.id }}">
                        {{ device_type.name }}
                        <span class="badge bg-primary badge-pill">{{ device_type.devicemodel_set.all | length }}</span>
                    </a>
                    <div class="collapse" id="collapse{{ device_type.id }}">
                        <div class="list-group-flush bg-light">
                            {% for device_model in device_type.devicemodel_set.all %}
                                <a class="list-group-item list-group-item-action {% if device_model == selected_device_model %}active{% endif %}"
                                   href="{% url 'device_model_list' %}?device_model={{ device_model.id }}"
                                   style="padding-left: 40px;">
                                    {{ device_model.manufacturer }} {{ device_model.name }}
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-9">
            {% if selected_device_model %}
                <h2>{{ selected_device_model.manufacturer }} {{ selected_device_model.name }}</h2>

                <div class="row">
                    <div class="col-md-9">
                        {% if selected_device_model.description %}
                            <p>{{ selected_device_model.description }}</p>
                        {% else %}
                            <p>Описание отсутствует</p>
                        {% endif %}
                    </div>
                    <div class="col-md-3">
                        {% if device_model.image %}
                            <img src="{{ device_model.image.url }}" alt="{{ device_model.name }}" width="200">
                        {% endif %}
                    </div>
                </div>

                <h4>Экземпляры устройств</h4>
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Инвентарный номер</th>
                        <th>ОПС</th>
                        <th>Индекс</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for device_instance in device_instances %}
                        <tr>
                            <td>{{ device_instance.inventory_number }}</td>
                            <td>{{ device_instance.department.name }}</td>
                            <td>{{ device_instance.department.index }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>Выберите модель устройства из списка слева.</p>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/core/edit_maintenance.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h1>Создать запись о ТО</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Сохранить изменения</button>
        </form>
    </div>
{% endblock %}

templates/core/edit_repair.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <h1>Создать запись о ремонте</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Сохранить изменения</button>
        </form>
    </div>
{% endblock %}

templates/core/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Добро пожаловать в систему учета устройств!</h1>
<p>Это главная страница приложения.</p>

<ul>
    <li><a href="{% url 'department_list' %}">Справочник ОПС</a></li>
    <li><a href="{% url 'device_model_list' %}">Справочник "Об устройстве"</a></li>
    </ul>

{% endblock %}

templates/core/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container w-25">
        <h2>Вход</h2>
        <form method="post" class="">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Войти</button>
        </form>
    </div>
{% endblock %}

templates/core/logout.html
{% extends 'base.html' %}

{% block content %}
<h2>Вы вышли</h2>
<a href="{% url 'login' %}">Войти снова</a>
{% endblock %}

templates/core/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>Профиль пользователя: {{ user.FIO }}</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Последние ремонты ({{ recent_repairs.count }})
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        {% for repair in recent_repairs %}
                        <li class="list-group-item">{{ repair.device }} - {{ repair.malfunction_type }} ({{ repair.date_repair|date:"d.m.Y" }})</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Последние ТО ({{ recent_maintenance.count }})
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        {% for maintenance in recent_maintenance %}
                        <li class="list-group-item">{{ maintenance.device }} - {{ maintenance.type }} ({{ maintenance.date|date:"d.m.Y" }})</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Статистика
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>За все время:</strong></p>
                            <p>Ремонты: {{ total_repairs }}</p>
                            <p>ТО: {{ total_maintenance }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>За последний месяц:</strong></p>
                            <p>Ремонты: {{ monthly_repairs }}</p>
                            <p>ТО: {{ monthly_maintenance }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}